AWSTemplateFormatVersion: 2010-09-09
Description: Palantir App API

Resources:
  apiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: Palantir API Built via Cloudformation Template
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: Palantir CF

  # authorizer using main Arcimoto user pool
  apiGatewayAuthorizer:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://s3.amazonaws.com/arcimoto-cloudformation/palantir-api/authorizer.yml
      Parameters:
        RestApiId: !Ref apiGateway

  # /v1
  apiResourceV1:
    Type: AWS::ApiGateway::Resource
    Properties: 
      ParentId: !GetAtt apiGateway.RootResourceId
      PathPart: v1
      RestApiId: !Ref apiGateway


  apiSectionAuthorities:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://s3.amazonaws.com/arcimoto-cloudformation/palantir-api/api_authorities.yml
      Parameters:
        AuthorizerId: !GetAtt apiGatewayAuthorizer.Outputs.apiGatewayAuthorizerId
        ParentResourceId: !Ref apiResourceV1
        RestApiId: !Ref apiGateway

  apiSectionFleets:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://s3.amazonaws.com/arcimoto-cloudformation/palantir-api/api_fleets.yml
      Parameters:
        AuthorizerId: !GetAtt apiGatewayAuthorizer.Outputs.apiGatewayAuthorizerId
        ParentResourceId: !Ref apiResourceV1
        RestApiId: !Ref apiGateway

  apiSectionLocations:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://s3.amazonaws.com/arcimoto-cloudformation/palantir-api/api_locations.yml
      Parameters:
        AuthorizerId: !GetAtt apiGatewayAuthorizer.Outputs.apiGatewayAuthorizerId
        ParentResourceId: !Ref apiResourceV1
        RestApiId: !Ref apiGateway

  apiSectionPermissions:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://s3.amazonaws.com/arcimoto-cloudformation/palantir-api/api_permissions.yml
      Parameters:
        AuthorizerId: !GetAtt apiGatewayAuthorizer.Outputs.apiGatewayAuthorizerId
        ParentResourceId: !Ref apiResourceV1
        RestApiId: !Ref apiGateway

  apiSectionRecalls:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://s3.amazonaws.com/arcimoto-cloudformation/palantir-api/api_recalls.yml
      Parameters:
        AuthorizerId: !GetAtt apiGatewayAuthorizer.Outputs.apiGatewayAuthorizerId
        ParentResourceId: !Ref apiResourceV1
        RestApiId: !Ref apiGateway

  apiSectionUsers:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://s3.amazonaws.com/arcimoto-cloudformation/palantir-api/api_users.yml
      Parameters:
        AuthorizerId: !GetAtt apiGatewayAuthorizer.Outputs.apiGatewayAuthorizerId
        ParentResourceId: !Ref apiResourceV1
        RestApiId: !Ref apiGateway

  apiSectionVehicles:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://s3.amazonaws.com/arcimoto-cloudformation/palantir-api/api_vehicles.yml
      Parameters:
        AuthorizerId: !GetAtt apiGatewayAuthorizer.Outputs.apiGatewayAuthorizerId
        ParentResourceId: !Ref apiResourceV1
        RestApiId: !Ref apiGateway

  # create stages and deploy
  # dev stage
  apiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: # this needs to depend on the last Method created or every method
      - apiSectionAuthorities
      - apiSectionFleets
      - apiSectionPermissions
      - apiSectionRecalls
      - apiSectionUsers
      - apiSectionVehicles
    Properties:
      RestApiId: !Ref apiGateway
      StageName: dev
      StageDescription:
        MethodSettings:
          - LoggingLevel: "INFO"
            HttpMethod: "*"
            MetricsEnabled: True
            ResourcePath: "/*"
        Variables:
          default_vehicles_vin_put_authority_id: 1
          default_vehicles_vin_put_group_id: 1
          func_authkey_vehicle_get: authkey_vehicle_get:dev
          func_backfill_s3_presigned_url_generate: backfill_s3_presigned_url_generate:dev
          func_backfill_state_machine_start: backfill_state_machine_start:dev
          func_create_authority: create_authority:dev
          func_firmware_version_get: firmware_version_get:dev
          func_firmware_version_vin_get: firmware_version_vin_get:dev
          func_fleets_accounting_department_code_create: fleets_accounting_department_code_create:dev
          func_fleets_accounting_department_code_delete: fleets_accounting_department_code_delete:dev
          func_fleets_accounting_department_codes_list: fleets_accounting_department_codes_list:dev
          func_fleets_fleet_update: fleets_fleet_update:dev
          func_fleets_vehicle_group_accounting_department_code_set: fleets_vehicle_group_accounting_department_code_set:dev
          func_fleets_vehicle_group_add_user: fleets_vehicle_group_add_user:dev
          func_fleets_vehicle_group_location_set: fleets_vehicle_group_location_set:dev
          func_fleets_vehicle_group_remove_user: fleets_vehicle_group_remove_user:dev
          func_fleets_vehicle_group_types_list: fleets_vehicle_group_types_list:dev
          func_fleets_vehicle_group_type_set: fleets_vehicle_group_type_set:dev
          func_get_authority: get_authority:dev
          func_get_telemetry_metrics_keys: get_telemetry_metrics_keys:dev
          func_get_telemetry_vehicle: get_telemetry_vehicle:dev
          func_get_vehicle_group: get_vehicle_group:dev
          func_gps_privacy_setting_get: gps_privacy_setting_get:dev
          func_list_authorities: list_authorities:dev
          func_list_vehicles: list_vehicles:dev
          func_list_telemetry_vehicles: list_telemetry_vehicles:dev
          func_list_vehicle_groups: list_vehicle_groups:dev
          func_locations_accounting_location_code_create: locations_accounting_location_code_create:dev
          func_locations_accounting_location_code_delete: locations_accounting_location_code_delete:dev
          func_locations_accounting_location_codes_list: locations_accounting_location_codes_list:dev
          func_locations_address_types_list: locations_address_types_list:dev
          func_locations_countries_list: locations_countries_list:dev
          func_locations_location_accounting_location_code_set: locations_location_accounting_location_code_set:dev
          func_locations_location_create: locations_location_create:dev
          func_locations_location_delete: locations_location_delete:dev
          func_locations_location_get: locations_location_get:dev
          func_locations_location_update: locations_location_update:dev
          func_locations_locations_list: locations_locations_list:dev
          func_managed_session_get: managed_session_get:dev
          func_managed_session_list: managed_session_list:dev
          func_managed_session_telemetry_get: managed_session_telemetry_get:dev
          func_note_create: note_create:dev
          func_notes_get: notes_get:dev
          func_recall_get: recall_get:dev
          func_recall_get_updated: recall_get_updated:dev
          func_recall_get_vehicle: recall_get_vehicle:dev
          func_recall_list: recall_list:dev
          func_recall_list_vehicle: recall_list_vehicle:dev
          func_recall_set_updated: recall_set_updated:dev
          func_remedy_get: remedy_get:dev
          func_remedy_list: remedy_list:dev
          func_sheer_id_verify_dl: sheer_id_verify_dl:dev
          func_sign_vehicle_token: sign_vehicle_token:dev
          func_step_wrapper_palantir: step_wrapper_palantir:dev
          func_user_groups_get: user_groups_get:dev
          func_users_ability_grant: users_ability_grant:dev
          func_users_create_user: users_create_user:dev
          func_users_add_permission_to_group: users_add_permission_to_group:dev
          func_users_add_preference_to_user: users_add_preference_to_user:dev
          func_users_add_user_to_group: users_add_user_to_group:dev
          func_users_remove_user_from_group: users_remove_user_from_group:dev
          func_users_disable_user: users_disable_user:dev
          func_users_enable_user: users_enable_user:dev
          func_users_group_create: users_group_create:dev
          func_users_group_delete: users_group_delete:dev
          func_users_group_get: users_group_get:dev
          func_users_groups_list: users_groups_list:dev
          func_users_permissions_abilities_list: users_permissions_abilities_list:dev
          func_users_permissions_ability_create: users_permissions_ability_create:dev
          func_users_permissions_ability_delete: users_permissions_ability_delete:dev
          func_users_permissions_ability_edit: users_permissions_ability_edit:dev
          func_users_permissions_ability_get: users_permissions_ability_get:dev
          func_users_permissions_list: users_permissions_list:dev
          func_users_preferences_list: users_preferences_list:dev
          func_users_profile_get: users_profile_get:dev
          func_users_profile_update: users_profile_update:dev
          func_users_resend_user_invite: users_resend_user_invite:dev
          func_users_remove_permission_from_group: users_remove_permission_from_group:dev
          func_users_user_get: users_user_get:dev
          func_users_user_mfa_sms_disable: users_user_mfa_sms_disable:dev
          func_users_user_mfa_sms_enable: users_user_mfa_sms_enable:dev
          func_users_user_mfa_totp_associate_token: users_user_mfa_totp_associate_token:dev
          func_users_user_mfa_totp_disable: users_user_mfa_totp_disable:dev
          func_users_user_mfa_totp_enable: users_user_mfa_totp_enable:dev
          func_users_user_mfa_totp_verify_token: users_user_mfa_totp_verify_token:dev
          func_users_users_list: users_users_list:dev
          func_vehicles_firmware_components_list: vehicles_firmware_components_list:dev
          func_vehicles_model_release_create: vehicles_model_release_create:dev
          func_vehicles_model_release_part_set: vehicles_model_release_part_set:dev
          func_vehicles_model_release_parts_get: vehicles_model_release_parts_get:dev
          func_vehicles_model_releases_list: vehicles_model_releases_list:dev
          func_vehicles_models_list: vehicles_models_list:dev
          func_vehicles_vehicle_model_release_set: vehicles_vehicle_model_release_set:dev
          func_vehicles_vehicle_part_set: vehicles_vehicle_part_set:dev
          func_telemetry_vehicles_timestream_get: telemetry_vehicles_timestream_get:dev
          func_vehicles_vehicle_shadow_synchronized: vehicles_vehicle_shadow_synchronized:dev

  # create staging stage and set to intial deployment
  apiGatewayStageStaging:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://s3.amazonaws.com/arcimoto-cloudformation/palantir-api/stage_staging.yml
      Parameters:
        ApiGatewayDeployment: !Ref apiGatewayDeployment
        RestApiId: !Ref apiGateway

  # create prod stage and set to initial deployment
  apiGatewayStageProduction:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://s3.amazonaws.com/arcimoto-cloudformation/palantir-api/stage_prod.yml
      Parameters:
        ApiGatewayDeployment: !Ref apiGatewayDeployment
        RestApiId: !Ref apiGateway

  # WAF
  wafWebACL:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: https://s3.amazonaws.com/arcimoto-cloudformation/palantir-api/waf.yml

  # WAF WebACL association to API stages
  apiWafWebACLAssociationDev:
    Type: AWS::WAFv2::WebACLAssociation
    DependsOn:
      - apiGatewayDeployment
    Properties: 
      ResourceArn: !Join
        - ""
        - - "arn:aws:apigateway:us-west-2::/restapis/"
          - !Ref apiGateway
          - "/stages/dev"
      WebACLArn: !GetAtt wafWebACL.Outputs.wafWebACLArn

  apiWafWebACLAssociationStaging:
    Type: AWS::WAFv2::WebACLAssociation
    DependsOn:
      - apiGatewayStageStaging
    Properties: 
      ResourceArn: !Join
        - ""
        - - "arn:aws:apigateway:us-west-2::/restapis/"
          - !Ref apiGateway
          - "/stages/staging"
      WebACLArn: !GetAtt wafWebACL.Outputs.wafWebACLArn

  apiWafWebACLAssociationProd:
    Type: AWS::WAFv2::WebACLAssociation
    DependsOn:
      - apiGatewayStageProduction
    Properties: 
      ResourceArn: !Join
        - ""
        - - "arn:aws:apigateway:us-west-2::/restapis/"
          - !Ref apiGateway
          - "/stages/prod"
      WebACLArn: !GetAtt wafWebACL.Outputs.wafWebACLArn

Outputs:
  apiGatewayInvokeURLDev:
    Value: !Sub https://${apiGateway}.execute-api.${AWS::Region}.amazonaws.com/dev
  apiGatewayInvokeURLStaging:
    Value: !Sub https://${apiGateway}.execute-api.${AWS::Region}.amazonaws.com/staging
  apiGatewayInvokeURLProd:
    Value: !Sub https://${apiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod