AWSTemplateFormatVersion: 2010-09-09
Description: Staging Stage - Palantir App API

Parameters:
  ApiGatewayDeployment:
    Type: String
  RestApiId: 
    Type: String

Resources:
  apiGatewayStageStaging:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: staging
      Description: Staging Stage
      RestApiId: !Ref RestApiId
      DeploymentId: !Ref ApiGatewayDeployment
      MethodSettings:
        - HttpMethod: "*"
          LoggingLevel: "ERROR"
          MetricsEnabled: True
          ResourcePath: "/*"
      Variables:
        default_vehicles_vin_put_authority_id: 1
        default_vehicles_vin_put_group_id: 1
        func_authkey_vehicle_get: authkey_vehicle_get:staging
        func_backfill_s3_presigned_url_generate: backfill_s3_presigned_url_generate:staging
        func_backfill_state_machine_start: backfill_state_machine_start:staging
        func_create_authority: create_authority:staging
        func_firmware_version_get: firmware_version_get:staging
        func_firmware_version_vin_get: firmware_version_vin_get:staging
        func_fleets_accounting_department_code_create: fleets_accounting_department_code_create:staging
        func_fleets_accounting_department_code_delete: fleets_accounting_department_code_delete:staging
        func_fleets_accounting_department_codes_list: fleets_accounting_department_codes_list:staging
        func_fleets_fleet_update: fleets_fleet_update:staging
        func_fleets_vehicle_group_accounting_department_code_set: fleets_vehicle_group_accounting_department_code_set:staging
        func_fleets_vehicle_group_add_user: fleets_vehicle_group_add_user:staging
        func_fleets_vehicle_group_location_set: fleets_vehicle_group_location_set:staging
        func_fleets_vehicle_group_remove_user: fleets_vehicle_group_remove_user:staging
        func_fleets_vehicle_group_types_list: fleets_vehicle_group_types_list:staging
        func_fleets_vehicle_group_type_set: fleets_vehicle_group_type_set:staging
        func_get_authority: get_authority:staging
        func_get_telemetry_metrics_keys: get_telemetry_metrics_keys:staging
        func_get_telemetry_vehicle: get_telemetry_vehicle:staging
        func_get_vehicle_group: get_vehicle_group:staging
        func_gps_privacy_setting_get: gps_privacy_setting_get:staging
        func_list_authorities: list_authorities:staging
        func_list_vehicles: list_vehicles:staging
        func_list_telemetry_vehicles: list_telemetry_vehicles:staging
        func_list_vehicle_groups: list_vehicle_groups:staging
        func_locations_accounting_location_code_create: locations_accounting_location_code_create:staging
        func_locations_accounting_location_code_delete: locations_accounting_location_code_delete:staging
        func_locations_accounting_location_codes_list: locations_accounting_location_codes_list:staging
        func_locations_address_types_list: locations_address_types_list:staging
        func_locations_countries_list: locations_countries_list:staging
        func_locations_location_accounting_location_code_set: locations_location_accounting_location_code_set:staging
        func_locations_location_create: locations_location_create:staging
        func_locations_location_delete: locations_location_delete:staging
        func_locations_location_get: locations_location_get:staging
        func_locations_location_update: locations_location_update:staging
        func_locations_locations_list: locations_locations_list:staging
        func_managed_session_get: managed_session_get:staging
        func_managed_session_list: managed_session_list:staging
        func_managed_session_telemetry_get: managed_session_telemetry_get:staging
        func_note_create: note_create:staging
        func_notes_get: notes_get:staging
        func_recall_get: recall_get:staging
        func_recall_get_updated: recall_get_updated:staging
        func_recall_get_vehicle: recall_get_vehicle:staging
        func_recall_list: recall_list:staging
        func_recall_list_vehicle: recall_list_vehicle:staging
        func_recall_set_updated: recall_set_updated:staging
        func_remedy_get: remedy_get:staging
        func_remedy_list: remedy_list:staging
        func_sheer_id_verify_dl: sheer_id_verify_dl:staging
        func_sign_vehicle_token: sign_vehicle_token:staging
        func_step_wrapper_palantir: step_wrapper_palantir:staging
        func_user_groups_get: user_groups_get:staging
        func_users_ability_grant: users_ability_grant:staging
        func_users_add_permission_to_group: users_add_permission_to_group:staging
        func_users_add_preference_to_user: users_add_preference_to_user:staging
        func_users_add_user_to_group: users_add_user_to_group:staging
        func_users_remove_user_from_group: users_remove_user_from_group:staging
        func_users_create_user: users_create_user:staging
        func_users_disable_user: users_disable_user:staging
        func_users_enable_user: users_enable_user:staging
        func_users_group_create: users_group_create:staging
        func_users_group_delete: users_group_delete:staging
        func_users_group_get: users_group_get:staging
        func_users_groups_list: users_groups_list:staging
        func_users_permissions_abilities_list: users_permissions_abilities_list:staging
        func_users_permissions_ability_create: users_permissions_ability_create:staging
        func_users_permissions_ability_delete: users_permissions_ability_delete:staging
        func_users_permissions_ability_edit: users_permissions_ability_edit:staging
        func_users_permissions_ability_get: users_permissions_ability_get:staging
        func_users_permissions_list: users_permissions_list:staging
        func_users_preferences_list: users_preferences_list:staging
        func_users_profile_get: users_profile_get:staging
        func_users_profile_update: users_profile_update:staging
        func_users_resend_user_invite: users_resend_user_invite:staging
        func_users_remove_permission_from_group: users_remove_permission_from_group:staging
        func_users_user_get: users_user_get:staging
        func_users_user_mfa_sms_disable: users_user_mfa_sms_disable:staging
        func_users_user_mfa_sms_enable: users_user_mfa_sms_enable:staging
        func_users_user_mfa_totp_associate_token: users_user_mfa_totp_associate_token:staging
        func_users_user_mfa_totp_disable: users_user_mfa_totp_disable:staging
        func_users_user_mfa_totp_enable: users_user_mfa_totp_enable:staging
        func_users_user_mfa_totp_verify_token: users_user_mfa_totp_verify_token:staging
        func_users_users_list: users_users_list:staging
        func_utility_palantir_version_latest_get: utility_palantir_version_latest_get:staging
        func_vehicles_firmware_components_list: vehicles_firmware_components_list:staging
        func_vehicles_model_release_create: vehicles_model_release_create:staging
        func_vehicles_model_release_part_set: vehicles_model_release_part_set:staging
        func_vehicles_model_release_parts_get: vehicles_model_release_parts_get:staging
        func_vehicles_model_releases_list: vehicles_model_releases_list:staging
        func_vehicles_models_list: vehicles_models_list:staging
        func_vehicles_vehicle_model_release_set: vehicles_vehicle_model_release_set:staging
        func_vehicles_vehicle_part_set: vehicles_vehicle_part_set:staging
        func_telemetry_vehicles_timestream_get: telemetry_vehicles_timestream_get:staging
        func_vehicles_vehicle_shadow_synchronized: vehicles_vehicle_shadow_synchronized:staging
