AWSTemplateFormatVersion: 2010-09-09
Description: Build WAFv2 WebACL for Palantir

Resources:
  apiWafWebACL: 
    Type: AWS::WAFv2::WebACL
    Properties: 
      Name: PalantirAPIWebACL
      Scope: REGIONAL
      Description: WebACL for Palantir API
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: PalantirACLMetric
      Rules: 
        - Name: AWSManagedAmazonIpReputation
          Priority: 0
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedAmazonIpReputationMetric
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAmazonIpReputationList
              ExcludedRules: []
        - Name: AWSManagedCommonRules
          Priority: 1
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedCommonRulesMetric
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
              ExcludedRules: []
        - Name: AWSManagedKnownBadInputs
          Priority: 2
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedKnownBadInputsMetric
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
              ExcludedRules: []

Outputs:
  wafWebACLArn: 
    Value: !GetAtt apiWafWebACL.Arn